FROM ubuntu:22.04 AS build

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      build-essential dpkg-dev libpulse-dev git autoconf libtool lsb-release curl sudo

RUN curl -s -L https://github.com/neutrinolabs/pulseaudio-module-xrdp/archive/v0.7.tar.gz | tar zx -C /opt/ \
    && mv /opt/pulseaudio-module-xrdp* /opt/pulseaudio-module-xrdp \
    && cd /opt/pulseaudio-module-xrdp \
    && ./scripts/install_pulseaudio_sources_apt.sh -d /opt/pulseaudio.src \
    && ./bootstrap \
    && ./configure PULSE_DIR=/opt/pulseaudio.src prefix=/usr \
    && make

####################################

FROM yama07/docker-ubuntu-lxde:22.04_ja

COPY --from=build \
    /opt/pulseaudio-module-xrdp/src/.libs/*.so /usr/libexec/pulseaudio-module-xrdp/

COPY --from=build \
    /opt/pulseaudio-module-xrdp/instfiles/load_pa_modules.sh /usr/libexec/pulseaudio-module-xrdp/

COPY --from=build \
    /opt/pulseaudio-module-xrdp/instfiles/pulseaudio-xrdp.desktop /etc/xdg/autostart/

RUN ln -s /usr/libexec/pulseaudio-module-xrdp/*.so  /usr/lib/pulse-*/modules/ \
    && echo "autospawn=yes" > /run/pulseaudio-enable-autospawn
