FROM ubuntu:14.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      lxde \
      xrdp \
      ibus \
      ibus-mozc \
      language-pack-ja-base \
      language-pack-ja \
      fonts-ipafont-gothic \
      fonts-ipafont-mincho \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* \
    && rm -rf /var/lib/apt/lists/*

# Expose RDP port
EXPOSE 3389

RUN echo "startlxde" > /etc/skel/.xsession

# Add JIS keyboard layout setting
ADD http://w.vmeta.jp/temp/km-0411.ini /etc/xrdp/km-0411.ini
RUN chown xrdp:xrdp /etc/xrdp/km-0411.ini \
    && chmod 644 /etc/xrdp/km-0411.ini \
    && ln -s /etc/xrdp/km-0411.ini /etc/xrdp/km-e0010411.ini \
    && ln -s /etc/xrdp/km-0411.ini /etc/xrdp/km-e0200411.ini

# Set locale
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
    && echo 'Asia/Tokyo' > /etc/timezone
RUN locale-gen ja_JP.UTF-8 \
    && echo 'LC_ALL=ja_JP.UTF-8' > /etc/default/locale \
    && echo 'LANG=ja_JP.UTF-8' >> /etc/default/locale
ENV LANG=ja_JP.UTF-8 \
    LANGUAGE=ja_JP:ja \
    LC_ALL=ja_JP.UTF-8

# Set default vars
ENV DEFAULT_USER=developer \
    DEFAULT_PASSWD=xrdppasswd

# Set sudoers for any user
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/ALL

# Change permission so that non-root user can add users and groups
RUN chmod u+s /usr/sbin/useradd \
    && chmod u+s /usr/sbin/groupadd

# Copy XRDP endpoint script
COPY endpoint.sh /opt/
CMD ["/opt/endpoint.sh"]
